name: Build Geode Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build mod
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings: geode-sdk/bindings
          bindings-ref: main
          combine: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AILevelGenerator
          path: '*.geode'
